%SLTRACE Trace streamlines generated by COMSOL and determine some quantities.
%   SLTRACE(fname), where fname is the filename of the saved COMSOL streamline
%   data, traces each streamline and evaluates quantities such as
%       start/end points
%       collection efficiency
%       streamline length
%   SLTRACE(fname, mode, zs, ze)
%       zs: starting z
%       ze: ending z
